---
title: "Problem 2"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    self_containted: true
---

```{r setup, include = FALSE}
library(flexdashboard)
library(plotly)
library(dplyr)
library(p8105.datasets)
library(ggplot2)

data("instacart")

instacart = instacart %>%
  sample_n(1000)

aisle_summary <- instacart %>%
  group_by(aisle) %>%
  summarise(order_count = n(), avg_days_since_prior_order = mean(days_since_prior_order, na.rm = TRUE)) %>%
  arrange(desc(order_count))

top_aisles <- aisle_summary[1:5, ]
```

Row {.tabset .tabset-fade}
-------------------------------------

### Scatter Plot

This scatter plot shows the relationship between days since the prior order and the order in which products were added to the cart.

```{r scatter-plot}
plot_ly(data = instacart, x = ~days_since_prior_order, y = ~add_to_cart_order, type = 'scatter', mode = 'markers',
        marker = list(size = 10, opacity = 0.5, line = list(width = 0.5, color = 'white'))) %>%
  layout(title = "Scatter Plot of Days Since Prior Order vs. Add to Cart Order",
         xaxis = list(title = "Days Since Prior Order"),
         yaxis = list(title = "Add to Cart Order"))
```

### Bar Plot

This bar plot displays the number of orders grouped by aisle.

```{r bar-plot}
bar_plot = ggplot(top_aisles, aes(x = reorder(aisle, -order_count), y = order_count)) +
  geom_bar(stat = "identity", aes(fill = aisle)) +
  labs(title = "Top 5 Aisles by Number of Orders", x = "Aisle", y = "Count") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))

ggplotly(bar_plot)
```

### Box Plot

This box plot illustrates the distribution of days since the prior order for each aisle.

```{r box-plot}
box_plot = plot_ly(data = instacart, 
                    y = ~days_since_prior_order, 
                    x = ~aisle, 
                    type = 'box', 
                    boxpoints = "all",
                    jitter = 0.3,
                    pointpos = -1.8) %>%
  layout(title = "Box Plot of Days Since Prior Order by Aisle",
         xaxis = list(title = "Aisle"),
         yaxis = list(title = "Days Since Prior Order"))

box_plot
```